version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of pyproject.toml
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
      
