repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python import sorting)
        files: \.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.306
    hooks:
      - id: ruff
        args: [--fix]  # automatically fix issues where possible

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10  # adjust to your Python version

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]  # optional, for docstring checks

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.26.1
    hooks:
      - id: markdownlint
        files: \.(md|markdown)$
